server:
  port: 9086

applications: user-service

turbine:
  appConfig: user-service,proxy
  cluster-name-expression: new String("default")
logging:
  level:
    org.springframework: debug
spring:
  application:
    name: turbine