server:
  port: 9981

spring:
  application:
    name: fraud-verifier
logging:
  level:
    org.springframework: info
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
          - health
eureka:
  instance:
    metadata-map:
      hint: test
      zone: zone1
