server:
  port: 9084

spring:
  application:
    name: ignored

eureka:
  client:
    healthcheck:
      enabled: true

logging:
  level:
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus