server:
  port: 9083
spring:
  application:
    name: proxy
  cloud:
    zookeeper:
    gateway:
      routes:
      - id: fraud
        uri: lb://fraud-verifier
        predicates:
        - Path=/fraud-verifier/**
        filters:
        - StripPrefix=1
      - id: ignored
        uri: lb://ignored
        predicates:
        - Path=/ignored/test/allowed
        filters:
        - StripPrefix=1
logging:
  level:
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus