server:
  port: 9083
spring:
  application:
    name: proxy
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      hint:
        default: test
#      sticky-session:
#        add-service-instance-cookie: true
    gateway:
      routes:
      - id: fraud
        uri: lb://fraud-verifier
        predicates:
        - Path=/fraud-verifier/**
        filters:
        - StripPrefix=1
#        - name: CircuitBreaker
#          args:
#            fallbackUri: xxx
#            routeId: xxxx
        - name: Retry
          args:
            retries: 3
      - id: ignored
        uri: lb://ignored
        predicates:
        - Path=/ignored/test/allowed
        filters:
        - StripPrefix=1

eureka:
  client:
    healthcheck:
      enabled: true
logging:
  level:
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
#hystrix:
#  command:
#    default:
#      circuitBreaker:
#        enabled: false