spring:
  application:
    name: demo-service
eureka:
  client:
    healthcheck:
      enabled: true
logging:
  level:
    org.springframework: info
server:
  port: 6666
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus