
spring:
  application:
    name: demo-service
  cloud:
    stream:
      bindings:
        input:
          destination: my_exchange
          content-type: application/json
        output:
          destination: my_other_exchange

logging:
  level:
    org.springframework: info
server:
  port: 6666
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus