spring:
  application:
    name: card-service
  cloud:
    loadbalancer:
      retry:
        enabled: true
      stats:
        micrometer:
          enabled: true
        publish-percentile-histogram: true
      ribbon:
        enabled: false
logging:
  level:
    org.springframework: info
server:
  port: 9080
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus