spring:
  application:
    name: card-service
  cloud:
    loadbalancer:
#      configurations: health-check
#      sticky-session:
#        add-service-instance-cookie: true
#      configurations: request-based-sticky-session

      ribbon:
        enabled: false
logging:
  level:
    org.springframework: info
server:
  port: 9080
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus