spring:
  application:
    name: card-service
  cloud:
    loadbalancer:
      eager-load:
        clients:
          - fraud-verifier
          - proxy
      #      clients:
      #        fraud-verifier:
      #          configurations: default
      #          retry:
      #            avoid-previous-instance: false
#      configurations: health-check
      zone: test
      sticky-session:
        add-service-instance-cookie: true
        instance-id-cookie-name:
      hint:
        default: test
      hint-header-name: X-Test
      health-check:
        refetch-instances: true
#      cache:
#        ttl: 60m
#        enabled: false
#        caffeine:
#          spec: maximumSize=200,expireAfterWrite=300s
logging:
  level:
    org.springframework: debug
    io.github.olgamaciaszek: debug
server:
  port: 9080
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
          - health
  server:
    port: 8888

