spring:
  application:
    name: card-service
  cloud:
    loadbalancer:
      zone: zone1
      healthcheck:
        path:
          default: /actuator/health
          ignored: /health
        interval: 40s
      ribbon:
        enabled: false
logging:
  level:
    org.springframework: info
server:
  port: 9080
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
#eureka:
#  instance:
#    metadata-map:
#      zone: zone1