spring:
  application:
    name: card-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      sticky-session:
        add-service-instance-cookie: true
logging:
  level:
    org.springframework: info
server:
  port: 9080
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus